### ISSUE TITLE
bb虾仁猪心

### ISSUE THREAD

**Issue by XXXFIRECUBE** [iMyOwn/teemo#4]

**Comment by XXXFIRECUBE** [comment]
为啥
E:\teemo>teemo -u （嘿嘿嘿） -p （嘿嘿嘿） -q 之后他
网络错误

**Comment by iMyOwn** [comment]
因为暂时需要在校园网环境下使用。
新版本马上出来，作为`ipgw`的插件，支持校内校外环境监控绩点
`ipgw`的插件机制正在编写，见 [#21](https://github.com/iMyOwn/ipgw/issues/21)

**Comment by iMyOwn** [comment]
已完成
